version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/dmts
    binary: dmts
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: "checksums.txt"
homebrew_casks:
  - repository:
      owner: kanmu
      name: homebrew-tools
    homepage: https://github.com/kanmu/demitas2
    description: Wrapper for ecspresso that creates task definitions at run time.
    license: MIT
    binaries:
      - dmts
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dmts"]
          end
