before:
  hooks:
    - go mod tidy
    # https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus
    - go get -u golang.org/x/sys
builds:
  - main: ./cmd/dmts
    binary: dmts
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-demitas2
    homepage: https://github.com/winebarrel/demitas2
    description: Wrapper for ecspresso that creates task definitions at run time.
    license: MIT
    install: |
      bin.install 'dmts'
