name: goreleaser
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Authenticate with GitHub App
        id: gh-app-auth
        uses: summerwind/gh-app-auth@main
        with:
          app-id: 244816
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          account: kanmu
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.gh-app-auth.outputs.token }}
